### ISSUE TITLE
Design a lighting chamber lid with slot for camera

### ISSUE THREAD

**Issue by vektorious** [vektorious/mbac#2]
To enable monitoring bacteria movements on a agar plate and we need a camera setup.
This should be combined with the [dark field lighting chamber](https://github.com/vektorious/mbac/issues/1) to take time lapse images for eventual analysis.

I suggest using a Raspberry Pi camera for this setup because the Raspberry Pi could be used to control the whole setup, host a image server and possibly perform on-line image analysis.

**Comment by vektorious** [comment]
I finished a first the fist version of the design! It still needs to be tested so we can see if it works like it is! 🎉 

![setup_v1](https://user-images.githubusercontent.com/20026476/39923136-ad89187c-5522-11e8-8842-73c06c6b67e8.gif)

**Comment by FernanFederici** [comment]
Hi Alex, would it be possible to have access to openscad files?
Thanks!
F
