### ISSUE TITLE
Detection of agar plate location in image

### ISSUE THREAD

**Issue by vektorious** [vektorious/mbac#4]
Before we can analyze movements of the bacteria over time we need to be able to identify agar plates in the pictures and maybe assign them labels.

I would suggest using [openCV for python](https://docs.opencv.org/master/d6/d00/tutorial_py_root.html) because python scripts go very well with the Raspberry Pi and would allow a complete automation of setup.  

I put together some [test pictures](https://drive.google.com/drive/folders/1Y14vlCDsIVxsvjT9EddqsrWoxS4w82-T?usp=sharing) 
which you can download and test the code with.

**Comment by 2alin** [comment]
I'm taking this one for a start. I'll probably have a PR before saturday. Then I'll continue with #5 and #6.

**Comment by vektorious** [comment]
Awesome 😄 🎉
